# Generated by Django 3.2 on 2021-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210507_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='grand_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
