# Generated by Django 3.2 on 2021-05-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210509_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qr_code',
            field=models.ImageField(blank=True, default='', upload_to='qr_codes'),
        ),
    ]
